knative/hack

library.sh

We are still getting a lot of 410's when doing update deps, we are using direct go mod mode, but there is a second checksum service that is also in-play. Removing that service.
Ref: https://twitter.com/mattomata/status/1323296883838627840

do not use the sum.golang.org service, too many 410s

---

library.sh

This was added in https://github.com/knative/test-infra/pull/2348, and we don't need it anymore since the Golang issue has been fixed.

Do not output json files since the Golang issue has been fixed

---

library.sh

Since https://storage.googleapis.com/knative-nightly/eventing/latest/eventing.yaml now returns 404

Use eventing-crds.yaml and eventing-core.yaml for eventing setup

---

library.sh

This PR shuts up spurious warnings in the client build, but still
let through other warnings.

chore: filter out bogus warnings about symlinks when doing a go mod tidy

---

e2e-tests.sh

Fixes #21 
- Don't overwrite `KO_DOCKER_REPO` if already set in current shell, and using GKE.

Don't overwrite KO_DOCKER_REPO if already set

---

library.sh

Reverts knative/hack#24
since eventing.yaml is back again https://console.cloud.google.com/storage/browser/knative-nightly/eventing%2Flatest%2F;tab=objects?prefix=&forceOnObjectsSortingFiltering=false

Revert "Use eventing-crds.yaml and eventing-core.yaml for eventing setup"

---

shell/assertions_test.go
shell/executor.go
shell/executor_test.go
shell/fail-example.sh
shell/prefixer.go
shell/prefixer_test.go
shell/project.go
shell/project_test.go
shell/types.go
test/presubmit-tests.sh

Fixes #28 
This shell out package should be treated as a bridge solution that will help Knative move out of using too much shell scripts. It will enable us using new Golang orchestrated tests, and build processes, and have the ability to shell out to scripts if needed.

Shell out package

---

foo/caller_not_allowed_test.go
shell/project.go

This is follow up to knative/hack#30 intended to disallow using this shell out package without control.
If a new place is required to use this package, an "allow PR" should be made to this repo first.
/cc @n3wscott

Validate usage of knative.dev/hack/shell

---

library.sh

Fixes #15 
This change will provide a hook to integrate with out-of-GOPATH projects to use k8s codegen and the changes are redirected back to the module.
Example integration in https://github.com/knative-sandbox/discovery/pull/125

Create a go path that points back to the local directory.

---

library.sh
test/unit/library-tests.sh

This will significantly reduce the size of the JUnit XML files produced by `gotestsum`. And note it will still include all the log messages for the failed test cases, so it does not impact the debuggability when the test flows fail.

Use testname format for gotestsum command

---

library.sh

-
-
-
/kind <kind>
Fixes #
Allows tools to be pulled in via go modules, which allows us to ensure the version of the tool used by various devs against the same commit matches exactly. When the tool is not found in a module, it will automatically fall back to the old logic.
The only instance where this will fail is if the module includes a different version of the tool than that installed in GOPATH.
Warns when non-hermetic mode is used, as it can be very difficult to main consistency across individual devs machines without
it.
User-visible changes in this PR:
None

Add hermetic go mod aware handling to run_go_tool

---

codegen-library.sh

If `GOBIN` is set to some directory, `go install` installs the binary
into GOBIN*1. And then, `hack/update-codegen.sh` (e.g. in serving repo)
fails due to missing `deepcopy-gen` binary installed by `go install` like:
```
--- Deepcopy Gen
hack/update-codegen.sh: line 84: /tmp/tmp.ZAaVX3NvIx/bin/deepcopy-gen: No such file or directory
```
Hence this PR sets `GOBIN` explicitly.
*1 https://golang.org/cmd/go/#hdr-Compile_and_install_packages_and_dependencies
> Executables are installed in the directory named by the GOBIN environment variable, which defaults to $GOPATH/bin or $HOME/go/bin if the GOPATH environment variable is not set.
```release-note
NONE
```
/cc @n3wscott

Set GOBIN in codegen-library.sh

---

library.sh

Fix #45 
`git describe` does not always work properly in all the repos,
especially when hot fix is required for the release process. After
this commit, when the PR is for master it will simply use git tag
without specifying the major version to get the latest tag instead.

Use git tag directly in master to get latest version

---

library.sh

A git tag was re-written in some upstream dependency.  Thus causing `GOPROXY=direct` to fail due to difference hashes.
We actually have the ability to explicitly ski  the proxy and sumdb for only `knative.dev` repos - so lets do that.

disable go's proxy and sumdb only for knative deps

---

library.sh

This function checks the status of pods in a namespace. It redirects STDERR to /dev/null, which makes failures hard to debug. This redirection is unnecessary as STDERR gets logged to console when using command substitution anyways. Not redirecting it would make failures easier to debug.

Don't redirect STDERR to /dev/null when querying pods

---

e2e-tests.sh
presubmit-tests.sh

Should allow downstream to append `-args`
https://golang.org/cmd/go/#hdr-Testing_flags
> To keep an argument for a test binary from being interpreted as a known flag or a package name, use -args (see 'go help test') which passes the remainder of the command line through to the test binary uninterpreted and unaltered.
> 
> For instance, the command
> 
> ```
> go test -v -args -x -v
> ```
> will compile the test binary and then run it as
> 
> ```
> pkg.test -test.v -x -v
> ```

go test flags should go first

---

library.sh

Add a comment to explain why we have a long wait_until_pods_running function
/cc @coryrc

Add a comment to explain why we have a long wait_until_pods_running function

---

codegen-library.sh

When running in CI the directory isn't always called 'pkg'
- :bug: Don't assume the pkg dir is named `pkg` in the codegen lib script
/kind bug
We just started using this script in knative/pkg and it looks like it doesn't work in this edge-case scenario where pkg is the repo being updated, but it's checked out as `/home/runner/work/knobots/knobots` on Github Actions.
https://github.com/knative-sandbox/knobots/runs/2448216473?check_suite_focus=true
/assign @n3wscott @dprotaso

Fix default codegen pkg dir

---

codegen-library.sh
library.sh

As per title, this supports the case where the repositories are still checked out onto a working `$GOPATH`.
1. Moves the module check above the GOPATH hackery. This took ages to fetch if running in a `$GOPATH` scenario, for whatever reason.
2. Make the GOPATH hackery skip itself if the repository is already checked out onto a legit `$GOPATH`. It's not necessary then.
3. Create a random directory for `$GOBIN` to not pollute the local bin directory even if running on a legit `$GOPATH`.
/assign @n3wscott @slinkydeveloper

Skip GOPATH hacks if the repository is already on GOPATH

---

codegen-library.sh

This should fix the current breakage in our nightly update scripts. Tested this in an empty docker container (as opposed to my system) to make sure it actually works.

Rollback random GOBIN and make it relative to GOPATH again

---

library.sh

- We currently hardcode that the vendor/ directory should be ignored by shellcheck, but users leveraging our test-infra should be able to customize which files should be ignored.

Allow for ignoring arbitrary files with shellcheck

---

library.sh

Fixed here: https://github.com/google/go-licenses/pull/65

go-licenses fixed file permissions so we no longer need our workaround

---

release.sh

Fixes https://github.com/knative/client/issues/1404
If we decide we want to make this configurable on a per-repo basis, it's pretty easy to go back and mark existing releases as `prerelease`; see https://github.com/knative/client/issues/1404#issuecomment-893754761 for an example script.

Stop performing pre-releases

---

library.sh

The current bash version check uses `-le 4` so it does not allow bash v4.
bash v4 should be supported so the script should use `-lt 4` instead.
/cc @xtreme-sameer-vohra @chizhg

Fix bash version check to allow v4 or later

---

release.sh
test/unit/release-tests.sh

Fixes: https://github.com/knative/hack/issues/97
This updates the release scripts to support two tag schemes:
- knative-vX.Y.Z
- vX.Y.Z
Note: when publishing to GitHub we look at the desired tag and if it matches `v1*` then we'll push the corresponding go module version tag.
The formula for the go module version is
- drop the major to 0
- add 27 to the minor
- patch version remains the same
See the document here: https://docs.google.com/document/d/1_khEw5_l8Zhh4FuY3NM56o_OM-cNWmmq1vXfLCxZqMA/edit?usp=sharing

Release use `knative-vX.Y.Z` tag and infer go module tag version automatically

---

library.sh
release.sh

it's aware of the new tag format and the manual jump from
v0.26 => v1.0
note: lates_version returns the tag which may now include prefixes

fix the latest_version function

---

library.sh

During CI setup it's sometimes useful to wait for an object
to exist before moving forward.
- Add `wait_until_object_exists` library function
```release-note
Add wait_until_object_exists library function.
Usage: 
wait_until_object_exists <kind> <name> <namespace>
```
**Docs**
```docs
wait_until_object_exists <kind> <name> <namespace>
```

Add `wait_until_object_exists` library function

---

schema/README.md

Many new contributors will have had experience with other k8s tooling like the Operator SDK and as
such may expect CRD generation to be a standard feature within the Knative tooling (myself being
an example). This change adds an extra explanation of Knative's position on CRD generation, and 
should make this tool more easily-discoverable via GitHub search by including keywords like
"CRD generation" and "controller-gen".
:broom: Update README.md
/kind documentation
This isn't assigned an issue, I needed to ask on Slack to find this repo so thought it would be worth clarifying for future new contributors.

chore: further explain knative CRD-generation support

---

release.sh

- :bug: Allows to see `TAG` and `TAG_RELEASE` from build_release func
/kind bug
Fixes https://github.com/knative-sandbox/kn-plugin-event/issues/77
In https://github.com/knative-sandbox/kn-plugin-event/pull/90 we had implemented a way to properly tag binaries and images from values of `$TAG` (only when `TAG_RELEASE==1`). Unfortunately, those variables aren't exported, so the build process can't see them.
This change exports those two variables, so the release script will work properly for kn event plugin.

:bug: Allows to see TAG from build_release func

---

e2e-tests.sh
test/e2e-tests.sh
test/presubmit-tests.sh

- :bug: No longer fail if teardown function isn't defined knative/hack#136
/kind bug
Fixes knative/hack#136

:bug: No longer fail if teardown function isn't defined

---

test/library_test.go

The unit tests for `library.sh` are failing, and it happened after the image update in https://github.com/knative/test-infra/pull/3014.
From the symptom the reason seems to be that `os.Interrupt` signal cannot be caught, since changing it to `os.Kill` will fix the tests. I wasn't able to figure out the root cause for it, so temporarily make the change to unblock PRs.

Temporarily fix the unit tests for library.sh

---

e2e-tests.sh
infra-library.sh

/kind cleanup
Granting cluster-admin manually is a limitation in GKE that Google has fixed since 1.12 and we are using gcloud service account keys instead of the Metadata Service
https://web.archive.org/web/20201026161748/https://cloud.google.com/kubernetes-engine/docs/how-to/role-based-access-control
https://github.com/istio/istio.io/pull/8442﻿

Cleanup unnecessary clusteradmin grants

---

presubmit-tests.sh

I don't remember why I had the wrong impression that regex used for `grep` didn't need `.`, apparently it needs...

Fix the regex used for matching GitHub Actions files

---

e2e-tests.sh

Signed-off-by: Paul S. Schweigert <paulschw@us.ibm.com>
Serving uses the `--enable-ha` flag in several of its e2e tests, but
parsing it out causes the flag to end up getting passed twice (once as
part of the script, and once from the parse out). So this PR fixes that
problem by not passing it as part of the e2e script commands.
For more details, see https://github.com/knative/serving/issues/12788
Fixes https://github.com/knative/serving/issues/12788
/assign @dprotaso

Skip passing enable-ha flag to test script

---

schema/example/schema.go
schema/example_test.go
schema/schema/generate_schema.go

- :bug: Fix bug
/kind bug
Today a `[]byte` field gets the schema `array` of integers between `0` and `255`.
If you look at `Secret` in k8s:
```
kubectl explain secret.data
KIND:     Secret
VERSION:  v1
FIELD:    data <map[string]string>
DESCRIPTION:
Data contains the secret data. Each key must consist of alphanumeric
characters, '-', '_' or '.'. The serialized form of the secret data is a
base64 encoded string, representing the arbitrary (possibly non-string)
data value here. Described in https://tools.ietf.org/html/rfc4648#section-4
```
Where the Go type is `map[string][]byte`.
cc @dprotaso @evankanderson @vaikas 
```release-note
```
**Docs**
```docs
```

Model []byte as strings

---

README.md
test/unit/presubmit-tests.sh

🧹 Addresses: https://github.com/knative/test-infra/issues/3383
Markdown linting and link checking is no longer performed in the `presubmit-tests.sh` script.
This PR updates the README to remove references to the now non-existent markdown checking. It also removes two seemingly unreferenced functions from the `presubmit-tests.sh` in the unit test folder for markdown link checking.

remove references to markdown checking

---

foo/output_test.go
foo/short_test.go
go.mod
infra-library.sh
library.sh
presubmit-tests.sh
release.sh
test/e2e-kind.sh
test/presubmit-tests.sh
test/unit/test-helper.sh

- :broom: Migrate to using the `go run` instead of `go install`
- :gift: Collecting JSONL, ANSI and nice HTML logs from all go tests
- :wastebasket: Removal of redundant manual race detection processing, and empty test suites handlers
/kind cleanup
Fixes #170

:broom: Migrate to using the `go run` instead of `go install`

---

library.sh

the warning text goes to stdout which breaks subshell invocations
/assign @cardil

drop warning in `go_run`

---

e2e-tests.sh
test/e2e-tests.sh
test/unit/e2e_helpers_test.go
test/unit/run_e2e_test.go
test/unit/scripts/smoke-test-custom-flag.bash
test/unit/sharedlib_test.go

- :bug: Fix for test failures of knative/serving#13292
/kind bug
Fixes tests for knative/serving#13292

:bug: Fix for test failures of knative/serving#13292

---

release.sh

/kind enhancement
cosign transparency log doesn't work properly without a certificate being supplied when verifying signatures.
```
REDACTED  MCW0CDP3YY  tmp  client  latest  $  COSIGN_EXPERIMENTAL=1 cosign verify-blob --signature checksums.txt.sig checksums.txt
WARNING: No valid entries were found in rekor to verify this blob.
Transparency log support for blobs is experimental, and occasionally an entry isn't found even if one exists.
We recommend requesting the certificate/signature from the original signer of this blob and manually verifying with cosign verify-blob --cert [cert] --signature [signature].
Error: verifying blob [checksums.txt]: could not find a valid tlog entry for provided blob, found 1 invalid entries
main.go:62: error during command execution: verifying blob …
```

Output certificate when signing binaries

---

release.sh

Part of https://github.com/knative/test-infra/issues/3536
- Allows mac binaries (GOOS=darwin) to be notarized.
- I need to upload the credentials to Google Secret Manager, load it to K8s and modify release/nightlies to use it.
/cc @cardil @kvmware

Notarize Mac binaries

---

release.sh

We have been signing our nightlies successfully for a few weeks now.
This PR removes the feature gate.
/cc @cardil @kvmware 
@knative/knative-release-leads Can you make sure this PR is merged before `knative/pkg` is cut?

Remove Signing Feature Gate

---

e2e-tests.sh

We read the version control from the go binary now

KO_DATA_PATH doesn't need to be set anymore

---

README.md
e2e-tests.sh
test/unit/presubmit_test.go
test/unit/run_e2e_test.go

This thing is so old and we don't use it so drop it.
In the past we would be install the Istio add-on available in GKE but we ended up installing it ourselves.

drop support for the istio add on flag

---

library.sh

We tend to add traps at various points in our test scripts.
The assumption we have is the trap will be executed when
external resources are in a certain state.
ie.
1. Setup Cluster - trap delete_cluster
2. Setup Knative - trap teardown_knative
3. Setup Tests   - trap dump_test_failure
Prior traps are executed in FIFO order so the cluster
would be torn down before the test dump would occur.
In LIFO order the test dump would occur first, then the
teardown of knative and then finally the cluster.
/assign @cardil 
/assign @upodroid

Trap calls are now executed in LIFO order

---

release.sh

Closes: https://github.com/knative/serving/pull/13408
Part of https://github.com/knative/test-infra/issues/3345
Some repos (eventing/serving and others) override the `ko` flags so this change calculates the image references directly from the yaml manifests that are uploaded.
/cc @dprotaso @kvmware

Calculate Image references properly

---

README.md
e2e-tests.sh
test/unit/e2e_helpers_test.go

- Don't `dump_metrics` by default - provide `on_success` & `on_failure` hooks as an alternative
- make env teardown optional
/hold going to test downstream

e2e script tweaks

---

e2e-tests.sh

This is useful for GitHub Actions that has it's own
method of diagnostics
/assign @kvmware

Allow tests to skip dumping resources on failure

---

presubmit-tests.sh
release.sh
test/unit/sharedlib_test.go

This change uploads the attesttation payload so we can view it with the job it was built from and we can see more clearly the cosign version we used.
/cc @kvmware

Upload attestations and print cosign version

---

shell/executor.go
shell/project_test.go

Remove ioutil for new go version: https://go.dev/doc/go1.16#ioutil
/kind cleanup

Cleanup: remove ioutil for new go version

---

library.sh
presubmit-tests.sh
test/unit/presubmit_test.go
test/unit/sharedlib_test.go
test/unit/update_deps_test.go

- :broom: Use extracted tools from knative.dev/toolbox
/kind cleanup
Related https://github.com/knative/toolbox/pull/3
Related https://github.com/knative/community/issues/1291

:broom: Use extracted tools from knative.dev/toolbox

---

release.sh

/cc @cardil @kvmware @BobyMCbobs 
The change in #268 broke image signatures. I'm also copying the image refs and attestations to the artifacts folder for easy verification.
I need to write a tool a to easily check sigstore signatures on all the nightly jobs.

Fix bug that broke signatures

---

test/e2e-kind.sh

- Installs Istio (ever since the istio addon stopped being supported, Istio hasn't been installed). The [recent probe additions to net-istio](https://github.com/knative-sandbox/net-istio/pull/1095) probably caused the tests to fail because Istio wasn't installed.
- Follows the same flow used by [knative/client](https://github.com/knative/client/blob/main/test/common.sh#L32)
Fixes #290 
Related issue #269

Install Istio for e2e tests

---

e2e-tests.sh
infra-library.sh
performance-tests.sh
presubmit-tests.sh
test/e2e-tests.sh
test/unit/presubmit_test.go
test/unit/sharedlib_test.go

- deprecate calling kubetest2 via kntest. It will take a while for the change to propagate.
- test PR with the change: https://github.com/knative/serving/pull/13329
Fixes #
/cc @cardil

Deprecate calling kubetest2 via kntest

---

release.sh

- :gift: Add function to release.sh to set highest semver as latest in github
Fixes https://github.com/knative/infra/issues/201

add function to set latest semver to latest

---

codegen-library.sh

There have been changes to the codegen scripts in k8s - we now need to add an exec bit to the following file
```
k8s.io/code-generator/generate-internal-groups.sh
```

include additional k8s bash file when updating exec permission

---

release.sh

Fixes errors like:
```
Setting latest release to highest semver
exit status 22
**************************************************
**** ERROR: error settomg v1.13.0 to 'latest' ****
************************************************** 
```
in the release jobs
- Don't hardcode serving, use env variables instead

Don't hardcode serving as the repo when setting highest semver

---

library.sh

Toolchain directive isn't necessary - and it's breaking go-licenses.
This is a workaround that drops it when updating dependencies.

drop toolchain directive

---

infra-library.sh

Currently we use the GKE default version for our GKE test clusters (https://cloud.google.com/kubernetes-engine/docs/release-notes-nochannel).
This can lead to problems when GKEs version is behind Knatives defined [min Kubernetes version](https://github.com/knative/pkg/blob/main/version/version.go#L36) and if repositories don't set it via the `--cluster-version` parameter.
This PR addresses it, and sets a Knative default for GKE test clusters.
Unfortunately this comes with the cost of maintaining this version - but can be reverted, when GKE uses a more recent version as default again.

Set default for GKE version to 1.28

---

library.sh
test/unit/update_deps_test.go

- :broom: Check licenses only, but not bundle them
/kind cleanup
Fixes knative/community#1441
```release-note
License files are no longer bundled with Knative sources, but only checked for validity
```

:broom: Check licenses only, but not bundle them

---

release.sh

We have been doing geo-replication for a long time, but it's costly and we don't tell our end-users about it.
It costs about 4x to store images in Artifact Registry vs Container Registry. 0.10 USD vs 0.026 USD for a multiregion GCS bucket. 
Storing in just gcr.io/knative-nightly which is the US multi-region should be sufficient.
/cc @dprotaso @cardil

Remove geo replication for GCR

---

codegen-library.sh
library.sh

- Fix premature codegen cleanup exit on 1
- Fix `truncate` param to be macos compatible
/cc @skonto @cardil

Fix premature codegen cleanup exit on 1

---

infra-library.sh

As per title, needed for 1.18 (https://github.com/knative/pkg/blob/ae2c6bcc1f5968766febc343903819b43d7ec903/version/version.go#L36)

Bump default GKE version to 1.31

---

infra-library.sh

- [release-1.16] Update GKE version to 1.29
Let's make sure we are able to run prow check on GKE. 
Fixes the following:
```
W0220 08:47:29.741775    4590 up.go:180] error resolving the release channel for "1.28": selected unknown release channel: EXTENDED, will proceed with no channel
Default change: VPC-native is the default mode during cluster creation for versions greater than 1.21.0-gke.1500. To create advanced routes based clusters, please pass the `--no-enable-ip-alias` flag
Default change: During creation of nodepools or autoscaling configuration changes for cluster versions greater than 1.24.1-gke.800 a default location policy is applied. For Spot and PVM it defaults to ANY, and for all other VM kinds a BALANCED policy is used. To change the default values use the …
```

[release-1.16] Update GKE version to 1.29
