knative/hack

- release.sh
ref: https://github.com/knative/test-infra/pull/2537
> Build stripped binaries to reduce sizes

- library.sh
Missed : https://github.com/knative/test-infra/pull/2532
> optimize unwanted file remove

- performance-tests.sh
> perf tests come from the image

- hack.go
- test/e2e-kind.sh
- test/e2e-tests.sh
- test/e2e/simple_e2e_test.go
- test/library_test.go
- test/presubmit-tests.sh
- test/presubmit-tests.sh.tmpl
- test/unit/e2e-custom-flag-tests.sh
- test/unit/library-tests.sh
- test/unit/presubmit-tests.sh
- test/unit/release-tests.sh
- test/unit/test-helper.sh
Also move the test files to the hack repo.
/cc @n3wscott
> Move tests to the hack repo

- README.md
As per title.
/assign @n3wscott
> Fix a few more occurrences of divisive language

- library.sh
Eventing and Serving define this function in their test scripts.
It could be useful for other projects as well.
References:
- https://github.com/knative/eventing/blob/12b783a7f2e7fbc54d20af56a53af80476e68df2/test/e2e-common.sh#L68-L74
- https://github.com/knative/serving/blob/631927b80dbd80c2ca6dc45b2638781ed805f919/test/e2e-upgrade-tests.sh#L34
> Add latest_version function

- release.sh
Unset KO_DOCKER_REPO to allow the tests to use their own
Fixes https://github.com/knative/eventing/issues/4563
/cc @cardil @danyinggu
> Unset KO_DOCKER_REPO to allow the tests to use their own

- microbenchmarks.sh
* Removed confusing echo
* Now printing results for each bench
* Specify count and benchtime
* Add a small comment that explains how to use it
Signed-off-by: Francesco Guardiani <francescoguard@gmail.com>
> Improve microbenchmarks.sh script

- library.sh
Starts to implement https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions
> adding github aware tags to new headers

- codegen-library.sh
- library.sh
In use here: https://github.com/knative-sandbox/discovery/pull/125
> adding codegen entry point for scripts to help clean dup code up

- library.sh
This reverts commit ea9c9a0cac5cc3735ed1dc6b019d58f72c0bfcd8 (#38)
> Revert "Add hermetic go mod aware handling to run_go_tool (#38)"

- README.md
- library.sh
- microbenchmarks.sh
As per title.
/assign @n3wscott
> Drop unnecessary occurrences of master

- release.sh
- test/e2e-kind.sh
To investigate https://knative.slack.com/archives/CA1DTGZ2N/p1619160369065000
> Add debug info for release.sh

- presubmit-tests.sh
Signed-off-by: Francesco Guardiani <francescoguard@gmail.com>
- Print java and maven version (followup of https://github.com/knative/test-infra/pull/2753)
> Print java and mvn version

- release.sh
Protect against accidentally printing token
/cc @chizhg 
/assign @chizhg
> Cleanup release script more

- OWNERS_ALIASES
- library.sh
- release.sh
- test/unit/release-tests.sh
> 1.0 Backports

- library.sh
- release.sh
- test/unit/release-tests.sh
- cherry-picking hack fixes due to tag naming scheme changes
> [release-0.26] hack cherry picks

- library.sh
- release.sh
- test/unit/release-tests.sh
cherry-picking hack fixes due to tag naming scheme changes
> [release-0.25] hack cherry picks

- library.sh
- release.sh
- test/unit/release-tests.sh
cherry-picking hack fixes due to tag naming scheme changes
> [release-0.24] hack cherry picks

- library.sh
- release.sh
Oddly the earlier cherry-pick didn't pull this in
> [release-0.26] Pull in missing functions

- library.sh
- release.sh
oddly the earlier cherry pick didn't pull this in
> [release 0.24] pull in missing functions

- library.sh
- release.sh
oddly the earlier cherry picks didn't pull this in
> [release 0.25] pull in missing functions

- presubmit-tests.sh
- :bug: Proper search for tags in Go files only
/kind bug
Fixes #134
> :bug: Proper search for tags in Go files only

- presubmit-tests.sh
Fixes: https://github.com/knative/test-infra/issues/3023﻿
> Print Commit Hashs on jobs.

- e2e-tests.sh
- infra-library.sh
Part of https://github.com/knative/test-infra/issues/3003
> Disable Logs/Metrics on GKE and Run Preemptible Nodes

- shell/project.go
Filenames shouldn't be used since we don't require repos to be checked out on the GOPATH
I got tripped up why upgrade tests couldn't run locally
> Look at package name when checking whether the shell package can be used

- README.md
- infra-library.sh
/cc @dprotaso @chizhg﻿
related to #138
> Enable opting out Preemptible/Spot GKE Worker Nodes

- release.sh
- test/unit/release-tests.sh
> Rename `release.sh` `master_version` function

- README.md
- library.sh
> Update kntest path after https://github.com/knative/test-infra/pull/3087

- library.sh
- :broom: Use `go install` instead of `get` for `run_go_tool` function.
- :wastebasket: remove the root check logic as `go install` does not change the `go.mod` file.
/kind cleanup
Fixes # https://github.com/knative/test-infra/issues/3113
> only use `install` for run_go_tool

- library.sh
- :bug: Fix the buoy invocation
/kind bug
Fixes #202
> :bug: Fix the buoy invocation

- library.sh
- :bug: Fixing go.mod foreach
/kind bug
Fixes #216
> :bug: Fixing go.mod foreach

- release.sh
nightly release failed with:
```
./hack/../vendor/knative.dev/hack/release.sh: line 314: SIGN_IMAGES: unbound variable
```
Signed-off-by: Pierangelo Di Pilato <pierdipi@redhat.com>
> Default `SIGN_IMAGES` variable to `false`

- release.sh
There were a few bugs from #231 that I have fixed.
I have enrolled one nightly for this. https://prow.knative.dev/prowjob?prowjob=aacfd670-4362-11ed-83e3-922558be6d19
/cc @cardil
> Fix some bugs in the notarizing logic

- presubmit-tests.sh
- test/unit/sharedlib_test.go
- :gift: Use Knative ls-tags tool
/kind enhancement
Related https://github.com/knative/actions/pull/72
```release-note
Use Knative ls-tags tool
```
> :gift: Use Knative ls-tags tool

- e2e-tests.sh
- infra-library.sh
- test/unit/presubmit_test.go
- :bug: Don't use NodeLocalDNS addon
/kind bug
Fixes partially https://github.com/knative-sandbox/kn-plugin-event/issues/242
> :bug: Don't use NodeLocalDNS addon

- e2e-tests.sh
- test/unit/presubmit_test.go
- :bug: Revert of #257
/kind bug
Related to https://github.com/knative-sandbox/kn-plugin-event/issues/242
> :bug: Revert of #257

- library.sh
Signed-off-by: Matthias Wessendorf <mwessend@redhat.com>
- remove sugar controller related snippets
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```
> No more sugar controller in upstream eventing

- release.sh
- test/unit/release_test.go
- test/unit/scripts/fake-build-release.bash
- test/unit/scripts/fake-presubmit-tests.bash
- test/unit/sharedlib_test.go
- :bug: Location-agnostic sign release
/kind bug
Fixes #240
Related to https://github.com/knative-sandbox/homebrew-kn-plugins/issues/134
> :bug: Location-agnostic sign release

- release.sh
- test/unit/release_test.go
- :bug: Find checksums file works with ARTIFACTS_TO_PUBLISH variable
/kind bug
Fixes https://github.com/knative/hack/issues/272
Follow up to https://github.com/knative/hack/pull/268
> :bug: Find checksums file works with ARTIFACTS_TO_PUBLISH variable

- release.sh
> Set GitHub Release Title to the version of the release

- library.sh
- presubmit-tests.sh
- test/unit/presubmit_test.go
- test/unit/sharedlib_test.go
- test/unit/update_deps_test.go
This reverts commit 1421f120c36bafe645a1b5e528382d25960218b4.
> Revert "Extract tools to knative.dev/toolbox (#280)"

- README.md
> Update e2e kntest link

- library.sh
- presubmit-tests.sh
- test/unit/presubmit_test.go
- test/unit/sharedlib_test.go
- test/unit/update_deps_test.go
As per title, test-infra repo https://github.com/knative/test-infra has been closed so use toolsbox instead.
> Replace test-infra with toolbox

- library.sh
Add support for `knative-extensions`
removed `knative-sandbox`
> Added knative-extensions

- test/e2e-kind.sh
> manual rename

- .github/workflows/knative-style.yaml
part of https://github.com/knative/infra/issues/207
> Manual shellcheck

- README.md
- cmd/script/README.md
- :gift: Docs on using vendorless Knative projects
/kind documentation
Fixes #322 
```release-note
It's possible to use vendorless projects in Knative
```
> :gift: Docs on using vendorless Knative projects

- codegen-library.sh
The codegen-library.sh script might be executed within a container that doesn't run as root in which case changing permissions is not allowed and the whole scripts fails.
This change gives opportunity to set the permissions in advance (e.g. during docker build) and then run this script successfully.
- Make files executable only if they're not executable yet
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```
> Make generate-groups.sh and generate-knative.sh executable conditionally

- release.sh
- :bug: Call set_latest_to_highest_semver after publishing a new release
/kind bug
Fixes #342
> :bug: Call set_latest_to_highest_semver after publishing a new release

- release.sh
- :bug: Set latest release only when publishing to Github
/kind bug
Follow up https://github.com/knative/hack/pull/343
Fixes https://github.com/knative/hack/issues/342
> :bug: Set latest release only when publishing to Github

- library.sh
- test/unit/presubmit_test.go
> bump various tools

- infra-library.sh
GKE folks recommend using a different region
Fixes: https://github.com/knative/serving/issues/14935
> switch default region to avoid instability

- infra-library.sh
- As per title, needed for 1.17.
> Bump K8s default to 1.30 (min)

- release.sh
- WIP: refactor release script to gh CLI
Per our chat earlier. The most questionable is to test `gh release create` for me.
> Refactor release script to gh CLI

- boilerplate.go.txt
- codegen-library.sh
- :lady_beetle: Skip whitespace changes in codegen
/kind bug
Fixes #419
> :lady_beetle: Skip whitespace changes in codegen

- infra-library.sh
- Bump min kube version to 1.32
Per https://github.com/knative/community/blob/main/mechanics/RELEASE-SCHEDULE.md#upcoming-releases
/assign @dprotaso
> Bump min kube version to 1.32
